project:
  type: book
lang: sv

book:
  title: "book_test"
  author: "Norah Jones"
  date: "2026-03-02"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-sections: true
    theme:
      - cosmo
      - brand
    tbl-cap-location: top
    tbl-cap-position: left
    fig-cap-location: bottom
    fig-cap-position: left

  pdf:
    documentclass: scrreprt

editor: visual

